### ISSUE TITLE
Improve Readme

### ISSUE THREAD

**Issue by maniac-tech** [Evie-Skinner18/happy_hacktoberfest_19#125]
The current Readme has basic information about the repo.

We should include the Contribution guidelines into the Readme making it a one place to search for information. Also, any first-time visitor will first overview the readme, which will help him understand the rules, and steps to proceed.

Considering, the repo is to help first-timers gain some experience, having different files may create confusion for them. A consolidated place for all the get-started-step will also help us avoid any duplication of information and a single place to update as we proceed.

Apart from the above said, we can also add a timestamp stating when was the website last updated, which can help us while creating issues, while we surf the website in cases of Bugs.

We should also be specifying some rules around code maintenance, as it is evident that people have not indented the code properly, naming conventions have went for a toss, and so on.

**Comment by maniac-tech** [comment]
@NitinNair89 Once we start with this, we can start addressing the Pull Requests and streamline the process into one single pipeline, making our lives easier.

**Comment by maniac-tech** [comment]
@Evie-Skinner18 Please let me know your views.

**Comment by NitinNair89** [comment]
> The current Readme has basic information about the repo.
> 
> We should include the Contribution guidelines into the Readme making it a one place to search for information. Also, any first-time visitor will first overview the readme, which will help him understand the rules, and steps to proceed.
> 
> Considering, the repo is to help first-timers gain some experience, having different files may create confusion for them. A consolidated place for all the get-started-step will also help us avoid any duplication of information and a single place to update as we proceed.
> 
> Apart from the above said, we can also add a timestamp stating when was the website last updated, which can help us while creating issues, while we surf the website in cases of Bugs.
> 
> We should also be specifying some rules around code maintenance, as it is evident that people have not indented the code properly, naming conventions have went for a toss, and so on.

Agreed. But we cannot update the readme file just to add a timestamp for the website version. Although keeping everything under readme would be easy to maintain and also easier for contributors, but I think we should keep the readme as a static content which does not get updated often. So adding contributor details in it will not satisfy this.

And if we maintain contributor details in separate file, we can dynamically fetch data from it and show it as a separate contributors web page.

Maybe we can create a "development" branch and live website should be in "master" branch. But again we cannot expect newbies to understand it and it might confuse them.

Any other ideas? We do have the kanban automated Project tab for tracking and ToDos.

**Comment by maniac-tech** [comment]
Let's have a separate file for contributor's and everything else merged into the ReadMe?
Speaking about the last updated state of website, we can have a time stamp somewhere in the webpage, or have a production/development environment?

What if we start putting up the process of development here?
This way we'll be able to maintain sanity in our live website, and also the newbies will understand how does production and something in development should be handled.
I'm suggesting this as I recently came across this ideology and trust me it has made my thought process way more clear, and understandable.

I'm open to suggestions and discussion.

**Comment by NitinNair89** [comment]
Yes, ReadMe will just have the description of this repo and the links for other guidelines. You can create "Code Of Conduct" document and mention the process of development there - including naming conventions and the likes.

This repo will definitely become a good start for hacktoberfest newbies when we have a full-fledged process in place. :smile: 

We also need to find out to how keep this repo or create other active repos for open-source. :slightly_smiling_face:

**Comment by maniac-tech** [comment]
Let's start by attaching a License here.

Rest can be put up on the Kanban board.

**Comment by NitinNair89** [comment]
> Let's start by attaching a License here.
> 
> Rest can be put up on the Kanban board.

I don't think I have access for adding license. @Evie-Skinner18 would have to do it.

GPL or MIT?
