### ISSUE TITLE
[Feature] Add Contributor's Page

### ISSUE THREAD

**Issue by maniac-tech** [Evie-Skinner18/happy_hacktoberfest_19#126]
Create a Contributor's Page on the website.

**Comment by maniac-tech** [comment]
@NitinNair89 I would like to work on this.

**Comment by NitinNair89** [comment]
> @Evie-Skinner18 I would like to work on this.

Go ahead :+1: 

Make it dynamic, so that it the page takes data from contributors.json file and creates the interface. This way, once the page is created. we no need to update it. The JSON file will serve the purpose of sending it data.

**Comment by maniac-tech** [comment]
Great, Will send you the PR as soon as it is done.

**Comment by NitinNair89** [comment]
We have 2 PRs for this issue now :man_facepalming: 

#129 and #128 

@SARAN-thala  and @maniac-tech  Please check.

**Comment by maniac-tech** [comment]
I see that @SARAN-thala has himself addressed #128 in #129, so I guess the issue #128 will resolve both.

**Comment by NitinNair89** [comment]
Something is missing. I don't see the layout as shown by @SARAN-thala when I visit the contributions page in this repo. Did it get overwritten @maniac-tech ?

Please send PR again after the changes.

**Comment by NitinNair89** [comment]
So I think partial work is done here by @SARAN-thala . @maniac-tech as discussed, you can move the code to contributors.html and then remove about.html and make it link to landing page about section. Once all done, will close this issue.

**Comment by maniac-tech** [comment]
Alright, let me see the current status of the website, as per what you just said, the contirbutor's page is as designed by me and not @SARAN-thala .

**Comment by maniac-tech** [comment]
How did the layout change again !?
@NitinNair89 
@Evie-Skinner18 

How merged a random code?
Check the navbar, it has 'BEACH TIME WOHOO'

**Comment by NitinNair89** [comment]
> How did the layout change again !?
> @NitinNair89
> @Evie-Skinner18
> 
> How merged a random code?
> Check the navbar, it has 'BEACH TIME WOHOO'

Hi @maniac-tech I have no idea. I guess @Evie-Skinner18 approved and merged the PR without proper review.

Can you fix is asap?

Hi @Evie-Skinner18 Please don't merge PRs which have conflicts.
