### ISSUE TITLE
[Bug] Fix the broken layout of the webpage

### ISSUE THREAD

**Issue by maniac-tech** [Evie-Skinner18/happy_hacktoberfest_19#127]
The current layout is broken with cards overlapping each other. Needs to be fixed.

**Comment by maniac-tech** [comment]
@Evie-Skinner18  I would like to pick this up

**Comment by NitinNair89** [comment]
Thanks @maniac-tech I had already sent the PR to fix it 1 hour ago :slightly_smiling_face:

**Comment by maniac-tech** [comment]
I did see the PR which raised, along with the Contributor's file.
But I don't understand why do we have cards on the webpage with z-index 2 containing placeholders?

**Comment by NitinNair89** [comment]
> I did see the PR which raised, along with the Contributor's file.
> But I don't understand why do we have cards on the webpage with z-index 2 containing placeholders?

I am not sure either. It was probably merged because it looked good, I have no idea :laughing: 

We can simply move it to your contributors webpage.

**Comment by maniac-tech** [comment]
Let's keep it on hold till the Contributor's page goes live, and then we can start cleaning up the layout.

What are your views?

**Comment by NitinNair89** [comment]
> Let's keep it on hold till the Contributor's page goes live, and then we can start cleaning up the layout.
> 
> What are your views?

Agreed. @WorkInProgress-Development  @Evie-Skinner18  Thoughts?

**Comment by SARAN-thala** [comment]
We need to fix this issue.

**Comment by NitinNair89** [comment]
> We need to fix this issue.

Yes. Waiting for @Evie-Skinner18  or @WorkInProgress-Development to review and merge the pull request

**Comment by NitinNair89** [comment]
@maniac-tech - Can you fix the layout and send a PR? I can review and merge

**Comment by maniac-tech** [comment]
Yes, I'll take care of it.

**Comment by maniac-tech** [comment]
You can assign this to me @NitinNair89

**Comment by NitinNair89** [comment]
> You can assign this to me @NitinNair89

Done! :slightly_smiling_face:

**Comment by maniac-tech** [comment]
Can we have a Code Freeze till I have the layout corrected?

**Comment by NitinNair89** [comment]
> Can we have a Code Freeze till I have the layout corrected?

Yup, we won't merge any PRs until layout is fixed. But do pull the latest version before you start development.

**Comment by maniac-tech** [comment]
Yes @NitinNair89  👍
