### ISSUE TITLE
Navbar fixes

### ISSUE THREAD

**Issue by maniac-tech** [Evie-Skinner18/happy_hacktoberfest_19#134]
Currently the navbar has spacing around it which should not be when the user scrolls down in the page.

The presence of the spacing, leads to wastage of Viewport, which can be otherwise used in the design itself.

**Comment by breezyfasano** [comment]
I can fix this ![bitmoji](https://render.bitstrips.com/v2/cpanel/042c5481-28ec-4d85-8f58-1e8f2376bfc6-162316b6-93cb-4342-89e1-7ce9926f033e-v1.png?transparent=1&palette=1&width=246)
