### ISSUE TITLE
Change the background

### ISSUE THREAD

**Issue by Evie-Skinner18** [Evie-Skinner18/happy_hacktoberfest_19#14]
First timers only! Change the colour or make it a funky image.

**Comment by Ashish0804** [comment]
@Evie-Skinner18 can u assign this issue to me?

**Comment by ferlu** [comment]
@Evie-Skinner18 hi! I just created a pull request for this issue. I think @Ashish0804 beat me to it, but it's nice to contribute for the 1st time so I wanted to give it a try. Happy hacktoberfest!:)

**Comment by Evie-Skinner18** [comment]
Brilliant thanks so much and well done on making your first PR! :grinning:
