### ISSUE TITLE
Fix Navigation Brand position

### ISSUE THREAD

**Issue by nimitpatel** [Evie-Skinner18/happy_hacktoberfest_19#148]
Elements are overlapping.

**Comment by NitinNair89** [comment]
Is this done?

**Comment by nimitpatel** [comment]
No  not by me

**Comment by NitinNair89** [comment]
> No not by me

Can you work on this then? This issue was referenced in your PR so I thought the fix was included :slightly_smiling_face:

**Comment by nimitpatel** [comment]
Sure  I'll try to fix it


And  i think  in  PR  it was referenced by mistake

I m  new to open source so  i was  just checking things  out  and  there
may be made a mistake and  it  got referenced

**Comment by prkhrv** [comment]
I can Fix it Please Assign this to me!!

**Comment by prkhrv** [comment]
#160 Fixed !! Please Check
