### ISSUE TITLE
Add a countdown timer

### ISSUE THREAD

**Issue by Evie-Skinner18** [Evie-Skinner18/happy_hacktoberfest_19#15]
This should count down the days til the end of Hacktoberfest.

**Comment by blackfile** [comment]
> This should count down the days til the end of Hacktoberfest.

I can work on this

**Comment by HALAVLUV** [comment]
#17 I added this feature in this pull request

**Comment by Evie-Skinner18** [comment]
Cheers @blackfile enjoy!

**Comment by cipher0942** [comment]
> This should count down the days til the end of Hacktoberfest.

I can make this

**Comment by blackfile** [comment]
completed [https://github.com/Evie-Skinner18/happy_hacktoberfest_19/pull/23](url)

**Comment by blackfile** [comment]
completed #23
