### ISSUE TITLE
Upgrade NavBar and footer

### ISSUE THREAD

**Issue by Sanjulapro** [Evie-Skinner18/happy_hacktoberfest_19#155]
Create a better eye catching UI for this page..
and try to Build responsive website..
The center part is too basic try something attractive.
the footer you must put [check](https://jetpack.com/2018/08/22/website-footer-tips/) this..
Normally in the footer we are putting copyright information.

Technically, websites don’t require footers to function properly; however, they do provide effective locations to add to your website’s functionality. This is especially true when combined with tools that help website owners create and deliver their content more efficient..

And I like to work in this issue

**Comment by Evie-Skinner18** [comment]
@Sanjulapro Please can you fix the issue you created with your footer before suggesting a new one? I've left you some feedback in your footer html file. All good learning! 👍
