### ISSUE TITLE
Change countdown timer text to a bright colour!

### ISSUE THREAD

**Issue by Evie-Skinner18** [Evie-Skinner18/happy_hacktoberfest_19#163]
I've just tried to change the text colour to yellow but it's not working. We have an ID for the countdown timer now:

` 
#countdown{
  margin-bottom: 0;
  color: #fdba04;
}`

Can anyone help change the text colour? doesn't have to be yellow just a bright contrasting colour will be great :grin:

**Comment by 2016CS101UET** [comment]
Cool I would love to do this!

**Comment by Evie-Skinner18** [comment]
Go for it!
