### ISSUE TITLE
Beer page!

### ISSUE THREAD

**Issue by Evie-Skinner18** [Evie-Skinner18/happy_hacktoberfest_19#176]
I've made a brand new page about beer :beer: . 

Feel free to add some funky bits and bobs to it! How about a gallery of some quality brews with some tasting notes under each one? Or an animation showing a delicious frothy pint in a glass?

Go wild! :beers: :dog2:

**Comment by cabaalexander** [comment]
Hello, Can I take this one ? 😅 I just need to be creative right ? 😬

**Comment by JacobMGEvans** [comment]
> Hello, Can I take this one ? 😅 I just need to be creative right ? 😬

@cabaalexander I suggest just doing it and making the PR

**Comment by JacobMGEvans** [comment]
Id say the best thing to do is # (reference with hashtag) the PR or the Issue so it shows you are working on it.

**Comment by elvensmile** [comment]
Oh, sorry, forgot to add #. But my PR is ready, could you please review it?

**Comment by Evie-Skinner18** [comment]
Ok will merge @elvensmile 's PR first and then save the issue for your contribution @cabaalexander . Thanks so much! Yep just need to be creative

**Comment by Jadson1197** [comment]
Hello, I added an effect on the beer page. Please, have a look on my PR #221
