### ISSUE TITLE
Clearer Contributors.html page description

### ISSUE THREAD

**Issue by Kbarias** [Evie-Skinner18/happy_hacktoberfest_19#182]
The list should be made clearer under "Why Hacktoberfest is awesome", where it includes colons and the beginning word of each line should be capitalized as such: 

Community: You are part of an inspiring community
Contacts: You can make new contacts
Events: There are many events around the world to meet with people of similar interests
Supporting: Supporting Open Source is an important part - since we all took advantage once
Awareness: It is good for the awareness of Open Source
T-shirt: You earn a limited edition T-Shirt

**Comment by Kbarias** [comment]
I will assign myself this issue.

**Comment by Evie-Skinner18** [comment]
Nice one go for it
