### ISSUE TITLE
Make a Hallowe'en page

### ISSUE THREAD

**Issue by Evie-Skinner18** [Evie-Skinner18/happy_hacktoberfest_19#189]
The Witching Hour is almost upon us! Do you celebrate Hallowe'en / el Dia de los Muertos / another seasonal festival that I don't know about? Let's share it with the world 🎃 💀 Cultural exchange!

**Comment by Evie-Skinner18** [comment]
NB this is for first timers only ✌️

**Comment by anth-dev** [comment]
I would like to help with this.

**Comment by Evie-Skinner18** [comment]
Go for it!

**Comment by anth-dev** [comment]
Page is completed and pull request has been submitted

**Comment by lemrkcz** [comment]
I would like to help too, if there is something left

**Comment by eprendes** [comment]
I'd like to make a Spooktober page!

**Comment by Evie-Skinner18** [comment]
@lemrkcz absolutely! First thing you can do is rebase your forked version of the project and add a link to the Hallowe'en page in the navbar. Currently we have @anth-dev 's Hallowe'en page but no way of navigating to it. Enjoy! :ghost:

**Comment by eprendes** [comment]
Would really enjoy doing something for this, if there's still some tasks available! :)

**Comment by lemrkcz** [comment]
> @lemrkcz absolutely! First thing you can do is rebase your forked version of the project and add a link to the Hallowe'en page in the navbar. Currently we have @anth-dev 's Hallowe'en page but no way of navigating to it. Enjoy! 👻

@Evie-Skinner18 Should it be placed in the nav-bar or in the event-dropdown?

**Comment by Evie-Skinner18** [comment]
@lemrkcz I don't mind at all, will have a look at your PR.

@eprendes yes definitely happy coding!

**Comment by eprendes** [comment]
Okay, made a PR for my new page! Please feel free to let me know if I made mistakes. I'm only halfway in to my first HTML class so it's basic :)
