### ISSUE TITLE
Add styles and functionality to competitions.html

### ISSUE THREAD

**Issue by Evie-Skinner18** [Evie-Skinner18/happy_hacktoberfest_19#198]
Currently it has no CSS, and when the user clicks the submit button we get a 404 error. Oh no!

## Options:
- Create a competitions.css file
- Create a competitions.js file for front end scripts
- Add an app.js file and use Node and Express to create a POST request which will take us somewhere when we click submit :thinking:

**Comment by Evie-Skinner18** [comment]
@daniellaskinner you want this one? :cheese: :grapes: :wine_glass:

**Comment by daniellaskinner** [comment]
Yes please!
