### ISSUE TITLE
Add link to the Day of the Dead page

### ISSUE THREAD

**Issue by Evie-Skinner18** [Evie-Skinner18/happy_hacktoberfest_19#222]
I accidentally merged this not realising that users cannot access the page! Would like a link in the navbar so people can see it.

NB first timers only!

**Comment by Anirudh-MV** [comment]
Hey, can I take this up? It's my first time contributing to open source

**Comment by Deepesh368** [comment]
This is my first time contributing to open source.I would like to learn to participate in Hacktoberfest

**Comment by SparshKat** [comment]
May i work on this? Is this issue still accepting PRs?
