### ISSUE TITLE
Console log on Contributors page

### ISSUE THREAD

**Issue by sarahtennis** [Evie-Skinner18/happy_hacktoberfest_19#255]
![Screen Shot 2019-10-28 at 8 39 46 PM](https://user-images.githubusercontent.com/19574304/67728333-46023700-f9c3-11e9-952e-a4a6178e433a.png)

**Comment by jeffkeilman** [comment]
I can handle this!

**Comment by jeffkeilman** [comment]
https://github.com/Evie-Skinner18/happy_hacktoberfest_19/pull/256

Fixes this!
