### ISSUE TITLE
Site is a bit broken... Help!

### ISSUE THREAD

**Issue by Evie-Skinner18** [Evie-Skinner18/happy_hacktoberfest_19#39]

**Comment by NitinNair89** [comment]
Hi,
I would like to work on this. Please assign to me. Also if you have a screenshot of your design then it would help me :smiley:

**Comment by Evie-Skinner18** [comment]
Hiya @NitinNair89 thanks for volunteering! I don't have a design but all I need is for the site to work properly :grin:

**Comment by NitinNair89** [comment]
Hi @WorkInProgress-Development,
Please also review this PR :smiley:

**Comment by WorkInProgress-Development** [comment]
Merged.

**Comment by NitinNair89** [comment]
Any issues here? The PR was merged and issue reopened? If any issues, let me know. I will fix it :smiley:

**Comment by WorkInProgress-Development** [comment]
Oops. Double-pressed the button.
