### ISSUE TITLE
Does anyone want to help maintain the project?

### ISSUE THREAD

**Issue by Evie-Skinner18** [Evie-Skinner18/happy_hacktoberfest_19#42]
Struggling to keep on top of all the wonderful pull requests!

**Comment by NitinNair89** [comment]
I am interested to collaborate with you. We can maintain the site together.

**Comment by WorkInProgress-Development** [comment]
I'd love to help maintain, although I won't be available 24/7.
I can help review pull requests and the like.

**Comment by Evie-Skinner18** [comment]
Thanks so much both! That's fine @WorkInProgress-Development no need to help 24/7 :+1:
