### ISSUE TITLE
Add more CSS

### ISSUE THREAD

**Issue by Evie-Skinner18** [Evie-Skinner18/happy_hacktoberfest_19#5]
This can be vanilla CSS, Bootstrap, or a mixture

**Comment by Sweta271097** [comment]
@Evie-Skinner18 Can I work on this?

**Comment by Evie-Skinner18** [comment]
course you can @Sweta271097 , enjoy!

**Comment by mohatagarvit** [comment]
Hi @Evie-Skinner18 , submitted this PR #30 adding animation, google search and link colors. Let know if there are any issues with this.

**Comment by Evie-Skinner18** [comment]
We need some styles for a class called Hacktoberfest that you can see in index.html `<div class="Hacktoberfest">Something Funky!</div>`

**Comment by Jxshvh** [comment]
Fun little project. Had a crack at it during break. not everything is in scope of the issue though, oops x)

**Comment by NitinNair89** [comment]
Hi @Sweta271097 - Are you working on this? This issue is assigned to you :slightly_smiling_face:

**Comment by RuchiraRuwantha** [comment]
Hey @Evie-Skinner18 @Sweta271097, I also like to help with this issue.

**Comment by NitinNair89** [comment]
Let's create and track things via separate issues.

Hi @RuchiraRuwantha - You can open issues and let us know if you are working on improving the website. :)
