### ISSUE TITLE
Create a better UI for the landing page

### ISSUE THREAD

**Issue by NitinNair89** [Evie-Skinner18/happy_hacktoberfest_19#58]
Create a better UI for the landing page to make it look cleaner

**Comment by sparkle-sparkle** [comment]
I'll do this one :-)

**Comment by Evie-Skinner18** [comment]
Go for it :grin:

**Comment by SparshKat** [comment]
Just did a few changes to the inital HTML to make it look less childish! :) please review

**Comment by NitinNair89** [comment]
> Just did a few changes to the inital HTML to make it look less childish! :) please review

Hi, please share the link where we can see how the landing page looks with your code changes.

**Comment by throwexceptions** [comment]
Hi @Evie-Skinner18 ,

I have updated the header for the index.html... please see my pull request... #107

**Comment by Evie-Skinner18** [comment]
Thank you all for helping :+1:

**Comment by sparkle-sparkle** [comment]
you're welcome ^_^
