### ISSUE TITLE
Avoid using Flex

### ISSUE THREAD

**Issue by maniac-tech** [Evie-Skinner18/happy_hacktoberfest_19#72]
We are currently using `display: flex` , we should rather use other available properties, as it is not widely supported by many browsers.

For details on which browsers support `display:flex`, check: https://caniuse.com/#search=flex

**Comment by Hganavak** [comment]
Really? Unless we're specifically targeting older versions of Internet Explorer, its pretty common practice to use flexbox nowadays :man_shrugging: 

Also note the first result of your link above is for the flex `gap` property, which I agree you should avoid. For what browsers actually support the flexbox layout, see: https://caniuse.com/#feat=flexbox

**Comment by NitinNair89** [comment]
I agree. CSS3 Flexbox is supported by most modern browsers and it gives us pretty good control on positioning and aligning elements on the page. The popular responsive framework Twitter Bootstrap's version 4 uses flexbox.

Closing this issue.
