### ISSUE TITLE
Update documents

### ISSUE THREAD

**Issue by NitinNair89** [Evie-Skinner18/happy_hacktoberfest_19#81]
Update documents with instructions regarding contributions so that everyone follows the same approach. This will help the maintainers to maintain the repo in a consistent manner.

**Comment by maniac-tech** [comment]
What if we start adding details in the PR stating if it is a new feature, or some correction.
Also, in cases of features, write a piece of information around it, and for correction add tags like `html` `css` to understand what has changed?

**Comment by maniac-tech** [comment]
Also, can we have a timestamp in the readme file for when was the website last updated?

**Comment by NitinNair89** [comment]
Thanks @maniac-tech . Check out the updated documents and let us know how we can streamline and improve this project as well as restrict spammy PRs
