### ISSUE TITLE
Improve the countdown timer interface

### ISSUE THREAD

**Issue by NitinNair89** [Evie-Skinner18/happy_hacktoberfest_19#85]
The countdown timer does not look that good right now. Please improve the UI :slightly_smiling_face: 

If you want to work on this issue, please add a comment below to get this issue assigned to you.

**Comment by dipanshu231099** [comment]
i would like to work on it

**Comment by NitinNair89** [comment]
> i would like to work on it

Go for it. Submit a PR once done.

**Comment by nimitpatel** [comment]
I would like to solve this issue

**Comment by NitinNair89** [comment]
> I would like to solve this issue

Thanks! It is already assigned to @dipanshu231099. We'll wait for a day for him to submit his PR. If no response, it will be assigned to you.

In the meantime, please feel free to create issues and improve the website. :slightly_smiling_face:

**Comment by nimitpatel** [comment]
> > I would like to solve this issue
> 
> Thanks! It is already assigned to @dipanshu231099. We'll wait for a day for him to submit his PR. If no response, it will be assigned to you.
> 
> In the meantime, please feel free to create issues and improve the website. 🙂

now can you assign me?

**Comment by NitinNair89** [comment]
> > > I would like to solve this issue
> > 
> > 
> > Thanks! It is already assigned to @dipanshu231099. We'll wait for a day for him to submit his PR. If no response, it will be assigned to you.
> > In the meantime, please feel free to create issues and improve the website. slightly_smiling_face
> 
> now can you assign me?

Done. Send in your PR after resolving conflicts

**Comment by nimitpatel** [comment]
> > > > I would like to solve this issue
> > > 
> > > 
> > > Thanks! It is already assigned to @dipanshu231099. We'll wait for a day for him to submit his PR. If no response, it will be assigned to you.
> > > In the meantime, please feel free to create issues and improve the website. slightly_smiling_face
> > 
> > 
> > now can you assign me?
> 
> Done. Send in your PR after resolving conflicts

those conflicts were not from my side  so i have created new PR for the same do check it @NitinNair89

**Comment by nimitpatel** [comment]
#148
