### ISSUE TITLE
Improve the footer of the page

### ISSUE THREAD

**Issue by NitinNair89** [Evie-Skinner18/happy_hacktoberfest_19#96]
Improve the footer of the website. Make it a look professional and standard :slightly_smiling_face:

**Comment by iryanjan18** [comment]
I would like to work on this section

**Comment by NitinNair89** [comment]
> I would like to work on this section

Sure. Go ahead! :+1:

**Comment by iryanjan18** [comment]
#108

**Comment by chrysillala** [comment]
hey, may i help? is there any specific design ideas for the footer? thanks

**Comment by NitinNair89** [comment]
Just standard footer design would be fine. If you have any good designs, use it

**Comment by BlackDevil98** [comment]
I would like to work on web development so i think i fix it...
