### ISSUE TITLE
Improve the About page

### ISSUE THREAD

**Issue by NitinNair89** [Evie-Skinner18/happy_hacktoberfest_19#97]
Improve the About page and fill it up with details of this project.

You can add "card" style layout to show contributor details. Maybe create a contributors.json file and read the data from it.

**Comment by SARAN-thala** [comment]
I'll do that

**Comment by NitinNair89** [comment]
> I'll do that

Sure. Go ahead! :+1:

**Comment by maniac-tech** [comment]
Hey @SARAN-thala any update here?

**Comment by SARAN-thala** [comment]
pushing now

**Comment by maniac-tech** [comment]
This is blocked on me right?
@NitinNair89

**Comment by NitinNair89** [comment]
Yeah, just do it :)

**Comment by Evie-Skinner18** [comment]
Thanks for this fantastic addition to the project!
